const apiPath = navigator.userAgent === 'ReactSnap' ? 'http://0.0.0.0:3003/calendar/api' : '/calendar/api';

export default {
  homePage: '/',
  loginPage: '/login',
  signupPage: '/signup',
  recoveryPasswordPage: '/recovery',
  activationPage: '/activation/:id',
  activationUrlPage: '/activation/',
  notFoundPage: '*',
  login: [apiPath, 'login'].join('/'),
  signup: [apiPath, 'signup'].join('/'),
  activation: [apiPath, 'activation/'].join('/'),
  activationRepeatEmail: [apiPath, 'activation/repeat-email/'].join('/'),
  activationChangeEmail: [apiPath, 'activation/change-email'].join('/'),
  auth: [apiPath, 'auth'].join('/'),
  deleteAuth: [apiPath, 'delete-auth'].join('/'),
  getDate: [apiPath, 'date/get-date'].join('/'),
  setDate: [apiPath, 'date/set-date'].join('/'),
  removeDate: [apiPath, 'date/remove-date'].join('/'),
  changeTime: [apiPath, 'date/change-time'].join('/'),
  addNewTime: [apiPath, 'date/add-new-time'].join('/'),
  removeTime: [apiPath, 'date/remove-time'].join('/'),
  removeRecord: [apiPath, 'date/remove-record'].join('/'),
  recording: [apiPath, 'recording'].join('/'),
  changePass: [apiPath, 'change-pass'].join('/'),
  changeUserData: [apiPath, 'change-user-data'].join('/'),
  cancelChangeEmail: [apiPath, 'cancel-change-email'].join('/'),
  recoveryPassword: [apiPath, 'recovery-password'].join('/'),
  checkRole: [apiPath, 'get-role'].join('/'),
};
